---
exclusions:
  - "**/.git/**/*"
  - "**/.github/**/*"
  - "**/target/**/*"
  - "**/RELEASE_INFO/**/*"
  - "**/.settings/**/*"
  - "**/.classpath"
  - "**/.project"

tasks:
  - selector:
      snapshot
    actions:
      - print
      - transform_version:
        - snapshot: remove
