---
exclusions:
  - "**/.git/**/*"
  - "**/.github/**/*"
  - "**/target/**/*"
  - "**/RELEASE_INFO/**/*"
  - "**/.settings/**/*"
  - "**/.classpath"
  - "**/.project"

tasks:
  - selector:
      snapshot
    actions:
      - print
      - transform_version:
        - add_major: 1
        - set_minor: 0
        - set_patch: 0
