name: Copyright check

on:
  pull_request:
    types: [opened, reopened, synchronize]
    branches:
      - 'master'
      - 'main'
      - 'develop'
      - 'release-*'

jobs:
  call-workflow-in-public-repo:
    uses: eclipse-kura/.github/.github/workflows/_shared-copyright-check.yml@main
    with:
      config-path: '.github/actions/setup/copyright-config.yml'
