name: Copyright check

on:
  pull_request:
    types: [opened, reopened, edited]
    branches:
      - 'master'

jobs:
  deploy-docs:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Install copyright-check
        run: pip install https://github.com/mattdibi/copyright-check/releases/download/0.1.1/copyright_check-0.1.1-py3-none-any.whl

      - name: Run check
        run: copyright-check -c .github/copyright-config.yml $(git diff --name-only HEAD^1 HEAD)
