name: Force merge
description: Merge a pull request when 3 committers post a comment with the command /force-merge

on:
  issue_comment:
    types: [created, edited]

jobs:
  force_merge:
    runs-on: ubuntu-latest

    steps:
      - name: List comments
        uses: actions/github-script@v7
        with:
          script: |
            const comments = await github.rest.issues.listComments({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo
            })

            console.log(comments)
