name: Force merge
description: Merge a pull request when 3 committers post a comment with the command /force-merge

on:
  issue_comment:
    types: [created, edited]

jobs:
  force_merge:
    runs-on: ubuntu-latest

    steps:
      - name: List comments
        uses: actions/github-script@v7
        with:
          script: |
            const comments = await github.rest.issues.listComments({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo
            })

            const votes = new Map();

            for(const comment of comments.data) {
              const hasPermissions = comment.author_association === 'MEMBER' || comment.author_association === 'OWNER'
              const hasCastedVote = comment.body === '/force-merge'

              if(hasPermissions && hasCastedVote) {
                const username = comment.user.login
                votes.set(username, 1);
              }
            }

            // Debug
            console.log(votes)
            console.log(votes.size)

            if(votes.size >= 1) {
              console.log("Reached quorum, performing force merge...")

              # Posting comment without other checks would throw the bot in an infinite loop
              # since it triggers on comment creation, some more investigation is needed
              #
              # await github.rest.issues.createComment({
              #   issue_number: context.issue.number,
              #   owner: context.repo.owner,
              #   repo: context.repo.repo,
              #   body: 'Reached quorum, performing force merge...'
              # })
            }
