name: Force merge
description: Merge a pull request when 3 committers post a comment with the command /force-merge

on:
  issue_comment:
    types: [created, edited]

jobs:
  force_merge:
    runs-on: ubuntu-latest

    steps:
      - name: List comments
        uses: actions/github-script@v7
        with:
          script: |
            const comments = await github.rest.issues.listComments({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo
            })

            const votes = new Map();

            for(const comment of comments.data) {
              const hasPermissions = comment.author_association === 'MEMBER' || comment.author_association === 'OWNER'
              const hasCastedVode = comment.body === '/force-merge'
              const username = comment.user.login

              if(votes.get(username)) {
                votes.set(username, votes.get(username) + 1);
              } else {
                votes.set(username, 1);
              }
            }

            console.log(votes)
