name: Force merge
description: Merge a pull request when 3 committers post a comment with the command /force-merge

on:
  issue_comment:
    types: [created, edited]

jobs:
  force_merge:
    runs-on: ubuntu-latest

    steps:
      - name: List comments
        uses: actions/github-script@v7
        with:
          script: |

            // TODO: Enhancement
            // Check if issue is PR, if not skip the rest of the workflow
            // see: https://docs.github.com/en/rest/issues/issues?apiVersion=2022-11-28#get-an-issue
            // For additional security, since we already have the info, we should check whether the author
            // is a member of the org. If not skip the workflow.

            // List all comments
            const comments = await github.rest.issues.listComments({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo
            })

            const votes = new Map();
            for(const comment of comments.data) {
              const hasPermissions = comment.author_association === 'MEMBER' || comment.author_association === 'OWNER'
              const hasCastedVote = comment.body === '/force-merge'

              if(hasPermissions && hasCastedVote) {
                const username = comment.user.login
                votes.set(username, 1);
              }
            }

            console.log(votes) // Debug

            // Add label to provide feedback about votes
            const labels = await github.rest.issues.listLabelsOnIssue({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo
            })
            const labelsToAdd = []
            for(const label of labels.data) {
              if(!label.name.startsWith('force-merge-votes-')) {
                labelsToAdd.push(label.name)
              }
            }

            if(votes.size >= 1 && votes.size < 3) {
                labelsToAdd.push("force-merge-votes-" + votes.size)
            }

            console.log(labelsToAdd) // Debug

            const result = github.rest.issues.setLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: labelsToAdd
            })

            // If quorum reached perform merge
            if(votes.size >= 1) {
              console.log("Reached quorum, performing force merge...")

              const result = await github.rest.pulls.merge({
                pull_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                merge_method: "squash"
              });
            }
