name: Force merge
description: Merge a pull request when N committers post a comment with the command /force-merge

on:
  issue_comment:
    types: [created, edited]

env:
  quorum: 3

jobs:
  force_merge:
    runs-on: ubuntu-latest

    steps:
      - name: Check pull request
        id: check-pr
        uses: actions/github-script@v7
        with:
          script: |
            // TODO: Enhancement
            // Check if issue is PR, if not skip the rest of the workflow
            // see: https://docs.github.com/en/rest/issues/issues?apiVersion=2022-11-28#get-an-issue
            // For additional security, since we already have the info, we should check whether the author
            // is a member of the org. If not skip the workflow.

            console.log("Checking PR")

      - name: Count votes
        id: count-votes
        uses: actions/github-script@v7
        with:
          script: |
            const comments = await github.rest.issues.listComments({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo
            })

            const votes = new Map();
            for(const comment of comments.data) {
              const hasPermissions = comment.author_association === 'MEMBER' || comment.author_association === 'OWNER'
              const hasCastedVote = comment.body === '/force-merge'

              if(hasPermissions && hasCastedVote) {
                const username = comment.user.login
                votes.set(username, 1);
              }
            }

            return votes.size

      - name: Set lables
        id: set-labels
        uses: actions/github-script@v7
        with:
          script: |
            const labels = await github.rest.issues.listLabelsOnIssue({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo
            })
            const labelsToAdd = []
            for(const label of labels.data) {
              if(!label.name.startsWith('force-merge-votes-')) {
                labelsToAdd.push(label.name)
              }
            }

            const votes = ${{ steps.count-votes.outputs.result }}
            if(votes >= 1 && votes < ${{env.quorum}}) {
                labelsToAdd.push("force-merge-votes-" + votes)
            }

            console.log(labelsToAdd) // Debug
            const result = github.rest.issues.setLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: labelsToAdd
            })

      - name: Check merge condition
        id: merge-condition
        with:
          script: |
            console.log(${{ steps.count-votes.outputs.result }} >= ${{env.quorum}}) // debug
            return ${{ steps.count-votes.outputs.result }} >= ${{env.quorum}}

      - name: Perform merge
        if: ${{ steps.merge-condition.outputs.result }}
        with:
          script: |
            await github.rest.pulls.merge({
              pull_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              merge_method: "squash"
            });
